sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RgulwpA7Njp+JyKY6+qNaFuSndrAGknQjFFJjFF1Q+yRPAxbctNthXBvmaY5umkpGnxljbcH9FkFWetd7mVeUh8yYF2c32DNCNkNveV2FoV5zdk2QT4XQ5pfxeBt/h6rLE4hVMoDw8RDQWCDbFzTPdMU6ZoOh+hVZ9mk6dZsGH9ybKNm9YIcdufxoYQ/kSJFQp1+/PuOMvWTnbFsB778qC2dQOcOe31mF5QsbXQ3aE045IWgxivWbSBNGA73t5/rfuNkF73CS1/sd7tjbG+NVnhE+MSWWMdtyJkoRT/gyrZPhmYvtY0+4fDCimqlOZLfBuZplkTJ9ZPRj4eJL7ZDA2cRsws2vqVttGG5eOxW35oLWV6j7goSS0j/7iJJB7bLMFVyccOhHE0tLSnVPTAun57b4Xjlma/P2diOx5USHrtGQl8387ig8Su5tfTaQ9uoYkZkBZRKSZoHFYbLdNaHIQAebR97K1OMdJUSEVb0Wj/rBAVfoxkirLgIqTv4b1jmx9P/mgcQsXIXC79NunNoUAGedi7tbANmQhjspqper7dvmUvqLIKHii5aWdkEVt1IZ1mMxdm/doitWbopyvjIz+/zgwAPdYOR1tjsW4oPN90gZFnb6vnyApxfLV3hdxaXEkYvx2jBqAcVYgpge4ck5sWBa4UNsXvqo+A4VBF5t/0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Reminiscences-of-Captain-Gronow_3798
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy